# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false

cache:
  directories:
    - $TRAVIS_BUILD_DIR/packrat/src
    - $TRAVIS_BUILD_DIR/packrat/lib
  packages: true

warnings_are_errors: false

os:
  - linux

r_packages:
  - covr

after_success:
  - Rscript -e 'library(covr); codecov()'
